
package com.asyf.demo.customer.client2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZETWSERV003", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "http://10.0.20.60:8000/sap/bc/srt/wsdl/flv_10002A101AD1/bndg_url/sap/bc/srt/rfc/sap/zetwserv003/100/zetwserv003/zetwserv003?sap-client=100")
public class ZETWSERV003_Service
    extends Service
{

    private final static URL ZETWSERV003_WSDL_LOCATION;
    private final static WebServiceException ZETWSERV003_EXCEPTION;
    private final static QName ZETWSERV003_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZETWSERV003");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.0.20.60:8000/sap/bc/srt/wsdl/flv_10002A101AD1/bndg_url/sap/bc/srt/rfc/sap/zetwserv003/100/zetwserv003/zetwserv003?sap-client=100");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZETWSERV003_WSDL_LOCATION = url;
        ZETWSERV003_EXCEPTION = e;
    }

    public ZETWSERV003_Service() {
        super(__getWsdlLocation(), ZETWSERV003_QNAME);
    }

    public ZETWSERV003_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZETWSERV003_QNAME, features);
    }

    public ZETWSERV003_Service(URL wsdlLocation) {
        super(wsdlLocation, ZETWSERV003_QNAME);
    }

    public ZETWSERV003_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZETWSERV003_QNAME, features);
    }

    public ZETWSERV003_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZETWSERV003_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZETWSERV003
     */
    @WebEndpoint(name = "ZETWSERV003")
    public ZETWSERV003 getZETWSERV003() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZETWSERV003"), ZETWSERV003.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZETWSERV003
     */
    @WebEndpoint(name = "ZETWSERV003")
    public ZETWSERV003 getZETWSERV003(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZETWSERV003"), ZETWSERV003.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZETWSERV003_EXCEPTION!= null) {
            throw ZETWSERV003_EXCEPTION;
        }
        return ZETWSERV003_WSDL_LOCATION;
    }

}
