
package com.asyf.demo.customer.client2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZETWSERV003", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZETWSERV003 {


    /**
     * 
     * @param zbukrs
     * @param izfy
     * @param idend
     * @param itAcdoca
     * @param idbeg
     */
    @WebMethod(operationName = "Zetw0003", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZETWSERV003:Zetw0003Request")
    @RequestWrapper(localName = "Zetw0003", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.asyf.demo.customer.client2.Zetw0003")
    @ResponseWrapper(localName = "Zetw0003Response", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.asyf.demo.customer.client2.Zetw0003Response")
    public void zetw0003(
            @WebParam(name = "Idbeg", targetNamespace = "")
                    String idbeg,
            @WebParam(name = "Idend", targetNamespace = "")
                    String idend,
            @WebParam(name = "ItAcdoca", targetNamespace = "", mode = WebParam.Mode.INOUT)
                    Holder<TableOfBicAzetw00012> itAcdoca,
            @WebParam(name = "Izfy", targetNamespace = "")
                    Integer izfy,
            @WebParam(name = "Zbukrs", targetNamespace = "")
                    String zbukrs);

}
