<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://www.baidu.com" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="ServiceDemoImplService"
                  targetNamespace="http://www.baidu.com">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.baidu.com"
                   elementFormDefault="unqualified" targetNamespace="http://www.baidu.com" version="1.0">

            <xs:element name="emrService" type="tns:emrService"/>

            <xs:element name="emrServiceResponse" type="tns:emrServiceResponse"/>

            <xs:complexType name="emrService">
                <xs:sequence>
                    <xs:element minOccurs="0" name="arg0" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="emrServiceResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>

        </xs:schema>
    </wsdl:types>
    <wsdl:message name="emrServiceResponse">
        <wsdl:part element="tns:emrServiceResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="emrService">
        <wsdl:part element="tns:emrService" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="ServiceDemo">
        <wsdl:operation name="emrService">
            <wsdl:input message="tns:emrService" name="emrService">
            </wsdl:input>
            <wsdl:output message="tns:emrServiceResponse" name="emrServiceResponse">
            </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ServiceDemoImplServiceSoapBinding" type="tns:ServiceDemo">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="emrService">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="emrService">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="emrServiceResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ServiceDemoImplService">
        <wsdl:port binding="tns:ServiceDemoImplServiceSoapBinding" name="ServiceDemoPort">
            <soap:address location="http://localhost:8080/services/ws/api"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>