
package com.asyf.demo.customer.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "ServiceDemo", targetNamespace = "http://www.baidu.com")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ServiceDemo {


    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "emrService", targetNamespace = "http://www.baidu.com", className = "com.asyf.demo.customer.client.EmrService")
    @ResponseWrapper(localName = "emrServiceResponse", targetNamespace = "http://www.baidu.com", className = "com.asyf.demo.customer.client.EmrServiceResponse")
    public String emrService(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
